name: user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  components: ^0.0.1
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  device_preview_plus: ^2.1.3
  onesignal_flutter: ^5.2.6
  pinput: ^5.0.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  easy_localization: ^3.0.7
  adaptive_theme: ^3.6.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  lifecycle: ^0.9.0
  impression: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/png/
    - assets/translations/
